# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ canon ]
  pull_request:
    branches: [ canon ]

jobs:
  check-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      uses: HorstBaerbel/action-ctest@1.1
      # These are optional (defaults displayed)
      with:
        sourcedir: '.'
        builddir: 'build'
        cmakeoptions: '--config Debug'
        ctestoptions: ''
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo pip install gcovr
    - name: Generate cobertura output
      run: |
        cd build/
        sudo gcovr -r .. -f '\.\./src' --cobertura cobertura.xml
        cat cobertura.xml
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: build/cobertura.xml