# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ canon ]
  pull_request:
    branches: [ canon ]

jobs:
  check-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create build dir
        run: mkdir build
      - name: Set up Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17
      - name: Build tests
        working-directory: build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17
          make chessatron_tests
      - name: Run tests
        working-directory: build
        run: ctest -c Release
